[project]
name = "modpack-devtools"
version = "0.1.0"
description = "Dev tools used to maintain Thunder modpack"
readme = "README.md"
dependencies = [
    "click>=8.1.0",
    "minecraft-launcher-lib>=6.0.0",
    "requests>=2.31.0",
]

[project.scripts]
thunder = "Thunder:main"


[tool.ruff]
line-length = 300
